FROM node:18-bookworm
WORKDIR /app
RUN apt update && apt install -y cmake libopenblas-dev
COPY package*.json ./
RUN npm ci --ignore-scripts
COPY . .
# RUN npm run build

ENTRYPOINT ["tail"]
CMD ["-f","/dev/null"]