name: Build Pre-build Packages for Linux

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

env:
  MKLROOT: '/opt/intel/mkl'

concurrency:
  group: release
  cancel-in-progress: false

jobs:
  build:
    environment: release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "true"
      - name: Install dependencies
        run: |
          curl -fsSL https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | sudo gpg --dearmor -o /etc/apt/keyrings/intel.gpg
          sudo sh -c 'echo deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/intel.gpg] https://apt.repos.intel.com/mkl all main > /etc/apt/sources.list.d/intel-mkl.list'
          sudo apt-get update
          sudo apt-get install -y intel-mkl-2020.4-912
          ls /opt/intel/mkl
      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: NPM Install
        run: npm ci --ignore-scripts
      - name: Build & test
        run: |
          npm run build:test
          ls build/Release
      - name: Build Release
        run: npm run prebuild-package -- --all
      - name: Get Version
        id: version
        run: |
          VERSION=$(node -p -e "require('./package.json').version")
          echo $VERSION
          echo VERSION=$VERSION >> "$GITHUB_OUTPUT"
      # - name: Upload to Release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     draft: true
      #     fail_on_unmatched_files: true
      #     files: prebuilds/*.tar.gz
      #     tag_name: "v${{ steps.version.outputs.VERSION }}"
