name: Build Pre-build Packages for Alpine

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: Prepare Image
      run: docker build -f Dockerfile.build -t faiss-build-alpine .
    - name: Build & test
      run: docker run --rm faiss-build-alpine
    - name: Build Release
      run: docker run --rm faiss-build-alpine run prebuild-package -- --all
