name: Build Pre-build Packages for Windows

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

env:
  WINDOWS_BASEKIT_URL: https:/registrationcenter-download.intel.com/akdlm/IRC_NAS/c961e083-5685-4f0b-ada5-c6cf16f561dd/w_BaseKit_p_2023.1.0.47256_offline.exe

concurrency:
  group: release
  cancel-in-progress: false

jobs:
  build:
    environment: release
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: Install MKL
      run: .github/workflows/install_mkl_windows.bat $WINDOWS_BASEKIT_URL "intel.oneapi.win.mkl.devel"
    - name: Setup Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: NPM Install
      run: npm ci --ignore-scripts
    - name: Build & test
      run: npm run build:test
    - name: Build Release
      run: npm run prebuild-package -- --all
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        fail_on_unmatched_files: true
        files: prebuilds/*.tar.gz
        tag_name: 'v0.2.2-alpha.0'
