name: Test Install & Import on Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        node: ['14', '16', '18', '20']
        distro:
          - ''
          - -buster
          - -bullseye
          - -alpine
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Check available builders
      run: docker buildx ls
    - name: NPM Pack
      run: npm pack
    - name: Rename Package
      run: mv faiss-node-*.tgz test-import/faiss-node.tgz
    - name: Build docker on node:${{ matrix.node }}${{ matrix.distro }}
      working-directory: ./test-import
      run: docker buildx build --platform linux/amd64,linux/arm64 -t test-import --build-arg BASE_IMAGE=node:${{ matrix.node }}${{ matrix.distro }} .
    - name: Inspect artifacts
      run: docker buildx imagetools inspect test-import
    - name: Run test
      working-directory: ./test-import
      run: docker run test-import
