name: Test Install & Import on Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    strategy:
      matrix:
        node: ['14', '16', '18', '20']
        distro:
          - ''
          - -buster
          - -bullseye
          - -alpine
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: NPM Pack
      run: npm pack
    - name: Rename Package
      run: mv faiss-node-*.tgz test-import/faiss-node.tgz
    - name: Build docker on node:${{ matrix.node }}-${{ matrix.distro }}
      working-directory: ./test-import
      run: docker build -t test-import --build-arg BASE_IMAGE=node:${{ matrix.node }}${{ matrix.distro }} .
    - name: Run test
      working-directory: ./test-import
      run: docker run test-import
